/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AbstractInput: typeof import('./src/components/AbstractInput.vue')['default']
    Add: typeof import('./src/pages/Add.vue')['default']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardBody: typeof import('bootstrap-vue-next/components/BCard')['BCardBody']
    BCardHeader: typeof import('bootstrap-vue-next/components/BCard')['BCardHeader']
    BCardText: typeof import('bootstrap-vue-next/components/BCard')['BCardText']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BFormText: typeof import('bootstrap-vue-next/components/BForm')['BFormText']
    BLink: typeof import('bootstrap-vue-next/components/BLink')['BLink']
    BListGroup: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroupItem']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    BPlaceholder: typeof import('bootstrap-vue-next/components/BPlaceholder')['BPlaceholder']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    BToast: typeof import('bootstrap-vue-next/components/BToast')['BToast']
    BTooltip: typeof import('bootstrap-vue-next/components/BTooltip')['BTooltip']
    CheckedCirclieIcon: typeof import('./src/icons/CheckedCirclieIcon.vue')['default']
    ChevronLeft: typeof import('./src/icons/ChevronLeftIcon.vue')['default']
    ChevronLeftIcon: typeof import('./src/icons/ChevronLeftIcon.vue')['default']
    ChevronRight: typeof import('./src/icons/ChevronRightIcon.vue')['default']
    ChevronRightIcon: typeof import('./src/icons/ChevronRightIcon.vue')['default']
    CirclieIcon: typeof import('./src/icons/CirclieIcon.vue')['default']
    copy: typeof import('./src/components/Home copy.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker.vue')['default']
    DeleteDialog: typeof import('./src/components/DeleteDialog.vue')['default']
    DropdownIcon: typeof import('./src/icons/DropdownIcon.vue')['default']
    Edit: typeof import('./src/pages/Edit.vue')['default']
    EditIcon: typeof import('./src/icons/EditIcon.vue')['default']
    Habit: typeof import('./src/components/Habit.vue')['default']
    HabitItem: typeof import('./src/components/HabitItem.vue')['default']
    Habits: typeof import('./src/pages/Habits.vue')['default']
    HInput: typeof import('./src/components/HInput.vue')['default']
    Home: typeof import('./src/pages/Home.vue')['default']
    IBi0Circle: typeof import('~icons/bi/0-circle')['default']
    IFa7SolidArrowLeft: typeof import('~icons/fa7-solid/arrow-left')['default']
    IFa7SolidArrowRight: typeof import('~icons/fa7-solid/arrow-right')['default']
    IFa7SolidCheck: typeof import('~icons/fa7-solid/check')['default']
    IFa7SolidCircle: typeof import('~icons/fa7-solid/circle')['default']
    IFa7SolidCircleMark: typeof import('~icons/fa7-solid/circle-mark')['default']
    IFa7SolidCircleNotch: typeof import('~icons/fa7-solid/circle-notch')['default']
    IFa7SolidDotCircle: typeof import('~icons/fa7-solid/dot-circle')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowItem: typeof import('./src/components/RowItem.vue')['default']
    SignIn: typeof import('./src/pages/SignIn.vue')['default']
    SignOut: typeof import('./src/pages/SignOut.vue')['default']
    SignUp: typeof import('./src/pages/SignUp.vue')['default']
    TodoItem: typeof import('./src/components/TodoItem.vue')['default']
    TrashIcon: typeof import('./src/icons/TrashIcon.vue')['default']
    UserIcon: typeof import('./src/icons/UserIcon.vue')['default']
  }
  export interface GlobalDirectives {
    vBModal: typeof import('bootstrap-vue-next/directives/BModal')['vBModal']
  }
}
