/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BListGroup: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroupItem']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    Edit: typeof import('./src/components/Edit.vue')['default']
    Habits: typeof import('./src/components/Habits.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    IBi0Circle: typeof import('~icons/bi/0-circle')['default']
    IFa7SolidArrowLeft: typeof import('~icons/fa7-solid/arrow-left')['default']
    IFa7SolidArrowRight: typeof import('~icons/fa7-solid/arrow-right')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
