/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Add: typeof import('./src/components/Add.vue')['default']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardBody: typeof import('bootstrap-vue-next/components/BCard')['BCardBody']
    BCardHeader: typeof import('bootstrap-vue-next/components/BCard')['BCardHeader']
    BCardText: typeof import('bootstrap-vue-next/components/BCard')['BCardText']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BListGroup: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroupItem']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    BTooltip: typeof import('bootstrap-vue-next/components/BTooltip')['BTooltip']
    CheckedCirclieIcon: typeof import('./src/components/CheckedCirclieIcon.vue')['default']
    ChevronLeft: typeof import('./src/components/ChevronLeft.vue')['default']
    ChevronRight: typeof import('./src/components/ChevronRight.vue')['default']
    CirclieIcon: typeof import('./src/components/CirclieIcon.vue')['default']
    copy: typeof import('./src/components/Edit copy.vue')['default']
    DeleteDialog: typeof import('./src/components/DeleteDialog.vue')['default']
    DropdownIcon: typeof import('./src/components/DropdownIcon.vue')['default']
    Edit: typeof import('./src/components/Edit.vue')['default']
    EditIcon: typeof import('./src/components/EditIcon.vue')['default']
    Habit: typeof import('./src/components/Habit.vue')['default']
    HabitItem: typeof import('./src/components/HabitItem.vue')['default']
    Habits: typeof import('./src/components/Habits.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    IBi0Circle: typeof import('~icons/bi/0-circle')['default']
    IFa7SolidArrowLeft: typeof import('~icons/fa7-solid/arrow-left')['default']
    IFa7SolidArrowRight: typeof import('~icons/fa7-solid/arrow-right')['default']
    IFa7SolidCheck: typeof import('~icons/fa7-solid/check')['default']
    IFa7SolidCircle: typeof import('~icons/fa7-solid/circle')['default']
    IFa7SolidCircleMark: typeof import('~icons/fa7-solid/circle-mark')['default']
    IFa7SolidCircleNotch: typeof import('~icons/fa7-solid/circle-notch')['default']
    IFa7SolidDotCircle: typeof import('~icons/fa7-solid/dot-circle')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignIn: typeof import('./src/components/SignIn.vue')['default']
    TodoItem: typeof import('./src/components/TodoItem.vue')['default']
    TrashIcon: typeof import('./src/components/TrashIcon.vue')['default']
  }
  export interface GlobalDirectives {
    vBModal: typeof import('bootstrap-vue-next/directives/BModal')['vBModal']
  }
}
