networks:
  proxy-network:
    external: true

services:
  flatten_app:
    build: .
    container_name: flatten_app
    ports:
      - 4173:4173
    restart: unless-stopped
    networks:
      - proxy-network
