networks:
  proxy-network:
    external: true

services:
  habit_app:
    build: .
    container_name: habit_app
    ports:
      - 8080
    restart: unless-stopped
    networks:
      - proxy-network
