networks:
  proxy-network:
    external: true

services:
  habits_app:
    build: .
    container_name: habits_app
    ports:
      - 4173
    restart: unless-stopped
    networks:
      - proxy-network
